parameters:
    app.hf_token: '%env(HUGGINGFACE_TOKEN)%'
    app.hf_url: '%env(HUGGINGFACE_API_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $hfToken: '%app.hf_token%'
            string $hfUrl: '%app.hf_url%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    Symfony\Component\RateLimiter\RateLimiterFactory $loginLimiter: '@limiter.login_limiter'
    App\EventSubscriber\SecuritySubscriber:
        arguments:
            $environment: '%kernel.environment%'
